name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers/001.txt
          key: test-key-01

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: mkdir -p "prime-numbers" && touch "prime-numbers/001.txt"

      - name: Use Prime Numbers
        run: ls prime-numbers
