name: Scheduled Lint Checks

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Cached Test Check
        id: cached-test-check
        uses: actions/cache@v3
        with:
          path: __dummy.txt
          key: test-complete-lint-${{ github.sha }}

      - name: Checkout Repo
        uses: actions/checkout@v3
        if: steps.cached-test-check.outputs.cache-hit != 'true'

      - name: Setup Node
        uses: actions/setup-node@v3
        if: steps.cached-test-check.outputs.cache-hit != 'true'
        with:
          node-version: 16
          cache: "yarn"

      - if: steps.cached-test-check.outputs.cache-hit != 'true'
        run: corepack enable # enable yarn

      - name: Run Checks Lint
        id: run-checks-lint
        if: steps.cached-test-check.outputs.cache-hit != 'true'
        run: echo "hey"

      # - uses: bahmutov/npm-install@v1
      # - name: Install dependencies
      #   if: steps.cached-test-check.outputs.cache-hit != 'true'
      #   run: yarn install

      # - name: Run Checks Lint
      #   id: run-checks-lint
      #   if: steps.cached-test-check.outputs.cache-hit != 'true'
      #   run: yarn lint
      #   continue-on-error: true

      - name: Alert on Failure
        if: ${{ failure() }}
        run: echo "Boom" # TODO: alert discord

      - name: Alert on Failure2
        if: ${{ failure() }}
        run: echo "Boom2" # TODO: alert discord

      - name: On Success, cache test hash
        if: ${{ success() }}
        run: touch "__dummy.txt"
