name: Caching Primes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: test-completed/dummy.txt
          key: test-complete-${{ steps.vars.outputs.sha_short }}

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: mkdir -p "test-completed" && touch "test-completed/dummy.txt"

      - name: Use Prime Numbers
        run: ls test-completed
