name: Caching Primes

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers/002.txt
          key: test-key-02

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: mkdir -p "prime-numbers" && touch "prime-numbers/002.txt"

      - name: Use Prime Numbers
        run: ls prime-numbers
